### PR TITLE
Fixed naming of Temp files for more than 5 cuts

### PR DESCRIPTION
**Pull request by Mainboand**
This one has occasionally been bothering me for years: When the number of video segments becomes double digit, the files are named wrongly (i.e. 'video_encode-0010.mkv' instead of 'video_encode-010.mkv'). This leads to mkvmerge failing in the final step.
The PR should fix this bug.

### CODE REVIEW

**Comment by gCurse** [comment]
Thanks, i'll look into this.
This shall NOT be merged before I merge cutinterface_new into master as I am not willing to rebase that branch again!

**Comment by Mainboand** [comment]
Great.
BTW I tested with the file Jurassic_World_18.06.03_20-00_uswnbc_180_TVOON_DE.mpg.HQ
But essentially any file with enough cuts should work.

**Comment by Mainboand** [comment]
Sorry for the missing parentheses. Editing in a browser window does have some disadvantages...
Can you name the files you tested with? With the Jurassic World recording that I mentioned, audio is just fine...

**Comment by gCurse** [comment]
I used  Jurassic_World_18.06.03_20-00_uswnbc_180_TVOON_DE.mpg.HQ, too.
Further testing with several avi from my trash folder:
Seems the order of the different parts is completely messed up. Example: One video started with the audio of the first scene but video from the end of the cut etc.
Very strange.

**Comment by gCurse** [comment]
Ah, now I see. Please have a look at the diff. You always use `self.copy_nr` even if it should read `self.encode_nr`.

It is impossible that it works for you.

**Comment by Mainboand** [comment]
Thanks for the hint. Yes, I'm very sorry. That was a stupid, avoidable copy/pasting mistake. :/
It should work better now. Please try again.

**Pull request merged**
